artifactory:
  persistence:
    enabled: true
    storageClass: "gp2"
  database:
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://artifactory-postgres.postgresql.svc.cluster.local:5432/artifactorydb
    user: artifactory
    password: artifactory123
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - artifactory.mycompany.com
    tls:
      - secretName: artifactory-tls
        hosts:
          - artifactory.mycompany.com
