name: CI Chatbot

on:
  push:
    branches:
      - dev
      - feature/*
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.x'

    # Install dependencies
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    # Run tests
    - name: Run tests
      run: |
          pytest

    # Build the Python package
    - name: Build package
      run: |
          python setup.py sdist bdist_wheel

    # Publish the package to a shared location (e.g., artifact or registry)
    - name: Publish package
      uses: actions/upload-artifact@v3
      with:
          name: python-package
          path: dist/